<?php
session_start();

// Prevent any output before JSON
ob_start();

if (!isset($_SESSION['user_id'])) {
    ob_clean();
    header('Content-Type: application/json');
    echo json_encode(['status' => 'error', 'message' => 'Unauthorized']);
    exit;
}

include '../database/db.php';

// Clear any output that might have been generated by includes
ob_clean();

header('Content-Type: application/json');

$userId = (int)$_SESSION['user_id'];
$currentPassword = trim($_POST['current_password'] ?? '');
$newPassword = trim($_POST['new_password'] ?? '');
$confirmPassword = trim($_POST['confirm_password'] ?? '');

// Validation - check all fields are provided
if (empty($currentPassword) || empty($newPassword) || empty($confirmPassword)) {
    ob_clean();
    header('Content-Type: application/json');
    echo json_encode(['status' => 'error', 'message' => 'Please fill in all fields']);
    exit;
}

// Validate new password length
if (strlen($newPassword) < 6) {
    ob_clean();
    header('Content-Type: application/json');
    echo json_encode(['status' => 'error', 'message' => 'Password must be at least 6 characters long']);
    exit;
}

// Validate new password and confirm password match
if ($newPassword !== $confirmPassword) {
    ob_clean();
    header('Content-Type: application/json');
    echo json_encode(['status' => 'error', 'message' => 'New password and confirm password do not match']);
    exit;
}

// Validate new password is different from current
if ($currentPassword === $newPassword) {
    ob_clean();
    header('Content-Type: application/json');
    echo json_encode(['status' => 'error', 'message' => 'New password must be different from current password']);
    exit;
}

// Verify current password BEFORE updating
if (!$conn) {
    ob_clean();
    header('Content-Type: application/json');
    echo json_encode(['status' => 'error', 'message' => 'Database connection failed']);
    exit;
}

$hashedCurrentPassword = md5($currentPassword);
$stmt = $conn->prepare("SELECT id, password FROM user_login WHERE id = ? AND password = ?");
if (!$stmt) {
    ob_clean();
    header('Content-Type: application/json');
    echo json_encode(['status' => 'error', 'message' => 'Database error: ' . $conn->error]);
    exit;
}

$stmt->bind_param('is', $userId, $hashedCurrentPassword);
$stmt->execute();
$result = $stmt->get_result();
$user = $result->fetch_assoc();
$stmt->close();

if (!$user) {
    ob_clean();
    header('Content-Type: application/json');
    echo json_encode(['status' => 'error', 'message' => 'Current password is incorrect']);
    exit;
}

// Update password
$hashedNewPassword = md5($newPassword);
$cols = [];
$cr = $conn->query("SHOW COLUMNS FROM user_login");
if ($cr) { 
    while ($r = $cr->fetch_assoc()) {
        $cols[] = $r['Field'];
    }
}
$hasLast = in_array('last_password_change', $cols);
$sql = $hasLast ? "UPDATE user_login SET password = ?, last_password_change = NOW() WHERE id = ?" : "UPDATE user_login SET password = ? WHERE id = ?";
$updateStmt = $conn->prepare($sql);

if (!$updateStmt) {
    ob_clean();
    header('Content-Type: application/json');
    echo json_encode([
        'status' => 'error',
        'message' => 'Database error: ' . $conn->error
    ]);
    exit;
}

if ($hasLast) {
    $updateStmt->bind_param('si', $hashedNewPassword, $userId);
} else {
    $updateStmt->bind_param('si', $hashedNewPassword, $userId);
}
// Note: Both cases use same bind_param since SQL is the same structure

if ($updateStmt->execute()) {
    // Clear default password flag from session
    unset($_SESSION['is_default_password']);
    
    ob_clean();
    header('Content-Type: application/json');
    echo json_encode([
        'status' => 'success',
        'message' => 'Password changed successfully'
    ]);
} else {
    ob_clean();
    header('Content-Type: application/json');
    echo json_encode([
        'status' => 'error',
        'message' => 'Failed to update password: ' . $updateStmt->error
    ]);
}

$updateStmt->close();
?>
