<?php
session_start();

// Prevent any output before JSON
ob_start();

if (!isset($_SESSION['user_id'])) {
    ob_clean();
    header('Content-Type: application/json');
    echo json_encode(['status' => 'error', 'message' => 'Unauthorized']);
    exit;
}

include '../database/db.php';
include 'include/employee_data.php';

// Clear any output that might have been generated by includes
ob_clean();

$leaveId = $_POST['leave_id'] ?? null;
$days = $_POST['days'] ?? null;
$leaveType = $_POST['leave_type'] ?? '';
$cancelReason = $_POST['cancel_reason'] ?? '';

// Validation
if (!$leaveId || !$days || !$leaveType) {
    ob_clean();
    header('Content-Type: application/json');
    echo json_encode(['status' => 'error', 'message' => 'Missing required parameters']);
    exit;
}

if (empty($cancelReason)) {
    ob_clean();
    header('Content-Type: application/json');
    echo json_encode(['status' => 'error', 'message' => 'Please provide a reason for cancellation']);
    exit;
}

// Only allow cancellation for Vacation Leave
if ($leaveType !== 'Vacation Leave') {
    ob_clean();
    header('Content-Type: application/json');
    echo json_encode(['status' => 'error', 'message' => 'Only Vacation Leave requests can be cancelled']);
    exit;
}

if (!$employeeDbId) {
    ob_clean();
    header('Content-Type: application/json');
    echo json_encode(['status' => 'error', 'message' => 'Employee ID not found']);
    exit;
}

if (!$conn) {
    ob_clean();
    header('Content-Type: application/json');
    echo json_encode(['status' => 'error', 'message' => 'Database connection failed']);
    exit;
}

try {
    // Verify the leave request belongs to the employee and is approved
    $checkStmt = $conn->prepare("SELECT id, start_date, status FROM leave_requests WHERE id = ? AND employee_id = ? AND status = 'Approved'");
    if (!$checkStmt) {
        ob_clean();
        header('Content-Type: application/json');
        echo json_encode(['status' => 'error', 'message' => 'Database error: ' . $conn->error]);
        exit;
    }
    
    $checkStmt->bind_param('ii', $leaveId, $employeeDbId);
    $checkStmt->execute();
    $checkResult = $checkStmt->get_result();
    $leaveRequest = $checkResult->fetch_assoc();
    $checkStmt->close();
    
    if (!$leaveRequest) {
        ob_clean();
        header('Content-Type: application/json');
        echo json_encode(['status' => 'error', 'message' => 'Leave request not found or cannot be cancelled']);
        exit;
    }
    
    // Check if start date is in the future
    $startDate = strtotime($leaveRequest['start_date']);
    $today = strtotime('today');
    
    if ($startDate <= $today) {
        ob_clean();
        header('Content-Type: application/json');
        echo json_encode(['status' => 'error', 'message' => 'Only future leave requests can be cancelled']);
        exit;
    }
    
    // Start transaction
    $conn->begin_transaction();
    
    try {
        // Check if cancellation_reason column exists, if not add it or use rejection_reason
        $checkCol = $conn->query("SHOW COLUMNS FROM leave_requests LIKE 'cancellation_reason'");
        $hasCancellationReason = $checkCol && $checkCol->num_rows > 0;
        
        // Add cancellation_reason column if it doesn't exist
        if (!$hasCancellationReason) {
            $addCol = $conn->query("ALTER TABLE leave_requests ADD COLUMN cancellation_reason text DEFAULT NULL AFTER rejection_reason");
            // If column was added, set flag to true
            if ($addCol) {
                $hasCancellationReason = true;
            }
        }
        
        // Update leave request status to Cancelled with reason
        if ($hasCancellationReason) {
            $updateStmt = $conn->prepare("UPDATE leave_requests SET status = 'Cancelled', cancellation_reason = ?, updated_at = NOW() WHERE id = ?");
        } else {
            // Use rejection_reason field if cancellation_reason doesn't exist
            $updateStmt = $conn->prepare("UPDATE leave_requests SET status = 'Cancelled', rejection_reason = ?, updated_at = NOW() WHERE id = ?");
        }
        
        if (!$updateStmt) {
            throw new Exception('Failed to prepare update statement: ' . $conn->error);
        }
        
        $updateStmt->bind_param('si', $cancelReason, $leaveId);
        if (!$updateStmt->execute()) {
            throw new Exception('Failed to update leave request: ' . $updateStmt->error);
        }
        $updateStmt->close();
        
        // Revert the used days in leave_allocations
        $currentYear = (int)date('Y');
        $revertStmt = $conn->prepare("UPDATE leave_allocations 
                                      SET used_days = GREATEST(0, used_days - ?),
                                          remaining_days = remaining_days + ?
                                      WHERE employee_id = ? 
                                      AND leave_type = 'Vacation Leave' 
                                      AND year = ?");
        
        if (!$revertStmt) {
            throw new Exception('Failed to prepare revert statement: ' . $conn->error);
        }
        
        $revertStmt->bind_param('iiii', $days, $days, $employeeDbId, $currentYear);
        if (!$revertStmt->execute()) {
            throw new Exception('Failed to revert leave credits: ' . $revertStmt->error);
        }
        $revertStmt->close();
        
        // Commit transaction
        $conn->commit();
        
        ob_clean();
        header('Content-Type: application/json');
        echo json_encode([
            'status' => 'success', 
            'message' => 'Leave request cancelled successfully. ' . $days . ' day(s) have been restored to your Vacation Leave credits.'
        ]);
        
    } catch (Exception $e) {
        // Rollback transaction on error
        $conn->rollback();
        throw $e;
    }
    
} catch (Exception $e) {
    ob_clean();
    header('Content-Type: application/json');
    echo json_encode(['status' => 'error', 'message' => 'Error: ' . $e->getMessage()]);
}
