<?php
session_start();

// Prevent any output before JSON
ob_start();

// Enable error reporting for debugging (remove in production)
error_reporting(E_ALL);
ini_set('display_errors', 0); // Don't display errors, but log them

if (!isset($_SESSION['user_id'])) {
    ob_clean();
    header('Content-Type: application/json');
    echo json_encode(['status' => 'error', 'message' => 'Unauthorized']);
    exit;
}

include '../database/db.php';
include 'include/employee_data.php';

// Clear any output that might have been generated by includes
ob_clean();

$leaveType = $_POST['leave_type'] ?? '';
$startDate = $_POST['start_date'] ?? '';
$endDate = $_POST['end_date'] ?? '';
$reason = $_POST['reason'] ?? '';

// Validation
if (empty($leaveType) || empty($startDate) || empty($endDate) || empty($reason)) {
    ob_clean();
    header('Content-Type: application/json');
    echo json_encode(['status' => 'error', 'message' => 'All fields are required']);
    exit;
}

// Validate dates
if (strtotime($startDate) > strtotime($endDate)) {
    ob_clean();
    header('Content-Type: application/json');
    echo json_encode(['status' => 'error', 'message' => 'End date must be after start date']);
    exit;
}

if (strtotime($startDate) < strtotime('today')) {
    ob_clean();
    header('Content-Type: application/json');
    echo json_encode(['status' => 'error', 'message' => 'Start date cannot be in the past']);
    exit;
}

if (!$employeeDbId) {
    ob_clean();
    header('Content-Type: application/json');
    echo json_encode(['status' => 'error', 'message' => 'Employee ID not found. Please ensure you are logged in correctly.']);
    exit;
}

if (!$conn) {
    ob_clean();
    header('Content-Type: application/json');
    echo json_encode(['status' => 'error', 'message' => 'Database connection failed']);
    exit;
}

try {
    // Calculate number of days
    $start = new DateTime($startDate);
    $end = new DateTime($endDate);
    
    // If start and end are the same, it's 1 day
    if ($startDate === $endDate) {
        $days = 1;
    } else {
        $end->modify('+1 day'); // Include end date
        $days = $start->diff($end)->days;
    }
    
    // Check if employee has available leave credits
    // BL and EL are deducted from VL credits
    $checkLeaveType = $leaveType;
    if ($leaveType === 'Bereavement Leave' || $leaveType === 'Emergency Leave') {
        $checkLeaveType = 'Vacation Leave'; // BL and EL use VL credits
    }
    
    if ($leaveType === 'Sick Leave' || $leaveType === 'Vacation Leave' || $leaveType === 'Bereavement Leave' || $leaveType === 'Emergency Leave') {
        $currentYear = (int)date('Y');
        
        // Check if leave_allocations table exists
        $checkAllocTable = $conn->query("SHOW TABLES LIKE 'leave_allocations'");
        if ($checkAllocTable && $checkAllocTable->num_rows > 0) {
            // Get remaining days for the specific leave type (VL for BL/EL)
            $remainingQuery = "SELECT remaining_days, total_days 
                              FROM leave_allocations 
                              WHERE employee_id = ? 
                              AND leave_type = ? 
                              AND year = ?";
            $remainingStmt = $conn->prepare($remainingQuery);
            
            if ($remainingStmt) {
                $remainingStmt->bind_param('isi', $employeeDbId, $checkLeaveType, $currentYear);
                $remainingStmt->execute();
                $remainingResult = $remainingStmt->get_result();
                $remainingRow = $remainingResult->fetch_assoc();
                $remainingStmt->close();
                
                if ($remainingRow) {
                    $remainingDays = (int)($remainingRow['remaining_days'] ?? 0);
                    $totalDays = (int)($remainingRow['total_days'] ?? 0);
                    
                    // If total days is 0, they have no leave allocation
                    if ($totalDays == 0) {
                        ob_clean();
                        header('Content-Type: application/json');
                        $message = 'You have no ' . ($checkLeaveType === 'Vacation Leave' && ($leaveType === 'Bereavement Leave' || $leaveType === 'Emergency Leave') ? 'Vacation Leave' : $leaveType) . ' credits allocated. This will be considered as UNPAID LEAVE. Please contact HR for leave allocation.';
                        echo json_encode([
                            'status' => 'error', 
                            'message' => $message
                        ]);
                        exit;
                    }
                    
                    // If remaining days is 0 or less, they've used all their leaves
                    if ($remainingDays <= 0) {
                        ob_clean();
                        header('Content-Type: application/json');
                        $message = 'You have no remaining ' . ($checkLeaveType === 'Vacation Leave' && ($leaveType === 'Bereavement Leave' || $leaveType === 'Emergency Leave') ? 'Vacation Leave' : $leaveType) . ' credits. This will be considered as UNPAID LEAVE. Please contact HR if you need to file an unpaid leave.';
                        echo json_encode([
                            'status' => 'error', 
                            'message' => $message
                        ]);
                        exit;
                    }
                    
                    // If requested days exceed remaining days
                    if ($days > $remainingDays) {
                        ob_clean();
                        header('Content-Type: application/json');
                        $creditType = ($checkLeaveType === 'Vacation Leave' && ($leaveType === 'Bereavement Leave' || $leaveType === 'Emergency Leave')) ? 'Vacation Leave' : $leaveType;
                        echo json_encode([
                            'status' => 'error', 
                            'message' => 'You only have ' . $remainingDays . ' remaining ' . $creditType . ' credit(s). You cannot request ' . $days . ' day(s).'
                        ]);
                        exit;
                    }
                } else {
                    // No leave allocation found for this leave type
                    ob_clean();
                    header('Content-Type: application/json');
                    $message = 'You have no ' . ($checkLeaveType === 'Vacation Leave' && ($leaveType === 'Bereavement Leave' || $leaveType === 'Emergency Leave') ? 'Vacation Leave' : $leaveType) . ' credits allocated. This will be considered as UNPAID LEAVE. Please contact HR for leave allocation.';
                    echo json_encode([
                        'status' => 'error', 
                        'message' => $message
                    ]);
                    exit;
                }
            }
        }
    }
    
    // Check if leave_requests table exists
    $checkTable = $conn->query("SHOW TABLES LIKE 'leave_requests'");
    if (!$checkTable || $checkTable->num_rows == 0) {
        // Create table if it doesn't exist
        $createTable = "CREATE TABLE IF NOT EXISTS `leave_requests` (
            `id` int(11) NOT NULL AUTO_INCREMENT,
            `employee_id` int(11) NOT NULL,
            `leave_type` varchar(100) NOT NULL,
            `start_date` date NOT NULL,
            `end_date` date NOT NULL,
            `days` int(11) NOT NULL,
            `reason` text NOT NULL,
            `status` enum('Pending','Approved','Rejected','Cancelled') DEFAULT 'Pending',
            `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
            `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
            PRIMARY KEY (`id`),
            KEY `idx_employee_id` (`employee_id`),
            KEY `idx_status` (`status`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci";
        
        if (!$conn->query($createTable)) {
            ob_clean();
            header('Content-Type: application/json');
            echo json_encode(['status' => 'error', 'message' => 'Failed to create table: ' . $conn->error]);
            exit;
        }
    } else {
        // Table exists, check if 'days' column exists
        $checkColumn = $conn->query("SHOW COLUMNS FROM `leave_requests` LIKE 'days'");
        if (!$checkColumn || $checkColumn->num_rows == 0) {
            // Add 'days' column if it doesn't exist
            $alterTable = "ALTER TABLE `leave_requests` ADD COLUMN `days` int(11) NOT NULL AFTER `end_date`";
            if (!$conn->query($alterTable)) {
                ob_clean();
                header('Content-Type: application/json');
                echo json_encode(['status' => 'error', 'message' => 'Failed to add days column: ' . $conn->error]);
                exit;
            }
        }
    }
    
    // Insert leave request
    $stmt = $conn->prepare("INSERT INTO leave_requests (employee_id, leave_type, start_date, end_date, days, reason, status) VALUES (?, ?, ?, ?, ?, ?, 'Pending')");
    
    if (!$stmt) {
        ob_clean();
        header('Content-Type: application/json');
        echo json_encode(['status' => 'error', 'message' => 'Prepare failed: ' . $conn->error]);
        exit;
    }
    
    $stmt->bind_param('isssis', $employeeDbId, $leaveType, $startDate, $endDate, $days, $reason);
    
    if ($stmt->execute()) {
        ob_clean();
        header('Content-Type: application/json');
        echo json_encode(['status' => 'success', 'message' => 'Leave request submitted successfully!']);
    } else {
        ob_clean();
        header('Content-Type: application/json');
        echo json_encode(['status' => 'error', 'message' => 'Failed to submit leave request: ' . $stmt->error]);
    }
    
    $stmt->close();
} catch (Exception $e) {
    ob_clean();
    header('Content-Type: application/json');
    echo json_encode(['status' => 'error', 'message' => 'Error: ' . $e->getMessage()]);
}
