-- Equipment decommissioning requests (employee submit; supervisor / inventory admin approve or decline)
CREATE TABLE IF NOT EXISTS `inventory_decommission_requests` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `employee_id` int(11) NOT NULL,
  `inventory_item_allocation_id` int(11) DEFAULT NULL,
  `company_name` varchar(255) DEFAULT NULL,
  `request_employee_name` varchar(255) NOT NULL,
  `equipment_name` varchar(255) NOT NULL,
  `item_code` varchar(100) NOT NULL,
  `equipment_type` varchar(150) DEFAULT NULL,
  `serial_number` text DEFAULT NULL,
  `equipment_description` text DEFAULT NULL,
  `brand_manufacturer` varchar(255) DEFAULT NULL,
  `item_date_received` date DEFAULT NULL,
  `date_decommissioning` date DEFAULT NULL,
  `reason_decommissioning` text NOT NULL,
  `test_1_notes` text DEFAULT NULL,
  `test_1_date` date DEFAULT NULL,
  `test_2_notes` text DEFAULT NULL,
  `test_2_date` date DEFAULT NULL,
  `test_3_notes` text DEFAULT NULL,
  `test_3_date` date DEFAULT NULL,
  `test_1_attachment_paths` text DEFAULT NULL,
  `test_2_attachment_paths` text DEFAULT NULL,
  `test_3_attachment_paths` text DEFAULT NULL,
  `attachment_path` varchar(500) DEFAULT NULL,
  `status` enum('pending','approved','declined') NOT NULL DEFAULT 'pending',
  `resolution_remark` text DEFAULT NULL,
  `reviewed_by_user_id` int(11) DEFAULT NULL,
  `reviewed_by_name` varchar(255) DEFAULT NULL,
  `resolved_at` datetime DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_decom_employee` (`employee_id`),
  KEY `idx_decom_status` (`status`),
  CONSTRAINT `fk_decom_employee` FOREIGN KEY (`employee_id`) REFERENCES `employees` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
